### PR TITLE
Updated README.md to reflect install process

### PR DESCRIPTION
**Pull request by ihunterklick**

### CODE REVIEW

**Comment by iDVB** [comment]
Please see my inline comments.

**Comment by ihunterklick** [comment]
So you don't want any sort of Install process? Just an updated Dependencies section?

**Comment by iDVB** [comment]
No more then what you would see on all other grunt tools:
https://github.com/gruntjs/grunt-contrib-copy

Try to mimic the same layout and wording.

**Comment by ihunterklick** [comment]
Ok done. Let me know if its not what you're looking for

**Pull request merged**
